version: '3.8'

services:
  app:
    image: ghcr.io/few-far/docker-images/statamic-php8.2.3-alpine3.17:1.7.2
    environment:
      SKIP_APP_CACHE: "true"
    volumes:
      - ./:/var/www/:delegated
    healthcheck:
      disable: true

  db:
    image: postgres:15.4-bullseye
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=testing"
      - "POSTGRES_PASSWORD=postgres"

  adminer:
    image: adminer:4.8.1
    ports:
      - 8080:8080

volumes:
  database:
